In [1]:
import numpy as np
from scipy.signal import convolve

w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

convolve(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

In [2]:
import numpy as np
from scipy.signal import correlate

w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

correlate(x, w, mode='valid')

array([48, 57, 24, 25, 16, 39])

In [3]:
import numpy as np
from scipy.signal import correlate

w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

correlate(x, w, mode='full')

array([ 6, 34, 51, 48, 57, 24, 25, 16, 39, 29, 13, 10])

In [4]:
import numpy as np
from scipy.signal import correlate

w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

correlate(x, w, mode='same')

array([34, 51, 48, 57, 24, 25, 16, 39, 29])

In [5]:
from scipy.signal import correlate2d

x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])
w = np.array([[2, 0], [0, 0]])

correlate2d(x, w, mode='valid')

array([[ 2,  4],
       [ 8, 10]])

In [6]:
import tensorflow as tf

x_4d = x.astype(np.float64).reshape(1, 3, 3, 1)
w_4d = w.reshape(2, 2, 1, 1)

c_out = tf.nn.conv2d (x_4d, w_4d, strides=1, padding="SAME")
c_out.numpy().reshape(3, 3)

2023-02-28 00:34:47.391990: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 00:34:48.210419: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-11.0/lib64:/usr/local/cuda-11.2/lib64
2023-02-28 00:34:48.210499: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-11.0/lib64:/usr/local/cuda-11.2/lib64
2023-02-28 00:34:48.

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [8]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
x = x.astype(np.float32).reshape(1, 4, 4, 1)

p_out = tf.nn.avg_pool2d(x, ksize=2, strides=2, padding="VALID")
p_out.numpy().reshape(2, 2)

array([[ 3.5,  5.5],
       [11.5, 13.5]], dtype=float32)

In [9]:
def relu(x):
    return np.maximum(x, 0)

x = np.array([-1, 2, -3, 4, -5])
relu(x)

In [12]:
x = np.array([-1, 2, -3, 4, -5])
r_out = tf.nn.relu(x)
r_out.numpy()

array([0, 2, 0, 4, 0])